AB:
    application:
        name: AggregationBlog
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/aggregated_blog
        username: napbad
        password: 123456


    data:
        redis:
            host: 127.0.0.1
            port: 6379
            password: 123456
            database: 0
    jwt:
        jwt-secret: Napbad
        jwt-expiration-ms: 86400000
        jwt-token-name: Authorization